CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    location TEXT NOT NULL,
    website_url TEXT NOT NULL,
    normalized_domain TEXT NOT NULL UNIQUE,
    phone TEXT,
    email TEXT,
    source_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT businesses_name_location_unique UNIQUE (normalized_name, location)
);

CREATE TABLE IF NOT EXISTS website_audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    audit_status TEXT NOT NULL DEFAULT 'success',
    blocked_reason TEXT,
    final_url TEXT,
    http_status INTEGER,
    https_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ssl_valid BOOLEAN NOT NULL DEFAULT FALSE,
    load_time_seconds DOUBLE PRECISION,
    mobile_viewport BOOLEAN NOT NULL DEFAULT FALSE,
    missing_title BOOLEAN NOT NULL DEFAULT FALSE,
    missing_meta_description BOOLEAN NOT NULL DEFAULT FALSE,
    broken_images_count INTEGER NOT NULL DEFAULT 0,
    broken_internal_links_count INTEGER NOT NULL DEFAULT 0,
    has_contact_form BOOLEAN NOT NULL DEFAULT FALSE,
    has_mailto BOOLEAN NOT NULL DEFAULT FALSE,
    has_phone_link BOOLEAN NOT NULL DEFAULT FALSE,
    outdated_design_signals JSONB NOT NULL DEFAULT '[]'::jsonb,
    unreachable BOOLEAN NOT NULL DEFAULT FALSE,
    blocked_or_challenged BOOLEAN NOT NULL DEFAULT FALSE,
    notes JSONB NOT NULL DEFAULT '[]'::jsonb,
    score INTEGER NOT NULL DEFAULT 100,
    issue_summary JSONB NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT website_audits_status_check CHECK (
        audit_status IN (
            'success',
            'unreachable',
            'blocked_or_challenged',
            'login_required',
            'paywalled',
            'timeout',
            'error'
        )
    )
);

CREATE TABLE IF NOT EXISTS outreach_drafts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    audit_id UUID NOT NULL REFERENCES website_audits(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    recipient_email TEXT,
    send_status TEXT NOT NULL DEFAULT 'draft',
    sent_at TIMESTAMPTZ,
    send_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT outreach_drafts_send_status_check CHECK (
        send_status IN ('draft', 'sent', 'failed', 'skipped')
    )
);

CREATE TABLE IF NOT EXISTS niche_city_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niche_name TEXT NOT NULL,
    city TEXT NOT NULL,
    country TEXT NOT NULL,
    query TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 100,
    target_leads_per_pack INTEGER NOT NULL DEFAULT 25,
    audit_limit INTEGER NOT NULL DEFAULT 10,
    last_run_at TIMESTAMPTZ,
    runs_count INTEGER NOT NULL DEFAULT 0,
    is_exhausted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT niche_city_queue_unique UNIQUE (niche_name, city, country),
    CONSTRAINT niche_city_queue_runs_count_check CHECK (runs_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_niche_city_queue_active_priority
    ON niche_city_queue (active, is_exhausted, priority DESC, last_run_at NULLS FIRST);

CREATE TABLE IF NOT EXISTS niche_city_seen_domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_item_id BIGINT NOT NULL REFERENCES niche_city_queue(id) ON DELETE CASCADE,
    normalized_domain TEXT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT niche_city_seen_domains_unique UNIQUE (queue_item_id, normalized_domain)
);

CREATE INDEX IF NOT EXISTS idx_niche_city_seen_domains_queue_item
    ON niche_city_seen_domains (queue_item_id);
